---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/web
    sys_packages:
      - mcrypt
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: redis, package: php5-redis }
      - { name: apc, package: php-apc }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
      - { name: "mongo", package: "pecl.php.net/mongo" }
      - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
    php_ppa: php5
  roles:
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - composer
    - phpunit
    - mysql
    - mongo
    - git
    - curl
    - sqlite
    - wget
    - rabbitmq
    - redis
